title: Turbo Mapper
email: kgoforth1503@gmail.com
description: >-
  Plot demand lines on turbocharger compressor maps.
baseurl: "/Turbo-Mapper"
url: "https://kforth.github.io/Turbo-Mapper"
repo_url: "https://github.com/kForth/Turbo-Mapper"
kofi_id: Q5Q01020LV
